version: '3'

services:
  file_db:
    image: mysql:5.7
    container_name: transfer_flow_db
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_password
      MYSQL_DATABASE: transfer_flow
      MYSQL_USER: user
      MYSQL_PASSWORD: my_secret_password

    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql
  graphite:
    image: graphiteapp/graphite-statsd
    container_name: graphite
    restart: always
    ports:
      - "2003:2003"
      - "1002:80"
      - "2004:2004"
      - "7002:7002"
    volumes:
      - ./data/graphite:/var/lib/graphite/storage
      - ./config/graphite:/opt/graphite/conf

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./config/grafana:/etc/grafana
    depends_on:
      - graphite
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_AUTH_DISABLE_LOGIN_FORM=false
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - TZ=UTC

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus/:/etc/prometheus/
      - ./data/prometheus/:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
    grafana-graphite-network:

volumes:
  dbdata:

