version: '3'

services:
  fuel_db:
    image: mysql:5.7
    container_name: transfer_flow_db
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_password
      MYSQL_DATABASE: transfer_flow
      MYSQL_USER: user
      MYSQL_PASSWORD: my_secret_password

    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata: