name: "Build the app then test API endpoints tests with Newman Tests"
on: [pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: test-db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '18'
          distribution: adopt

      - name: Build application
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/transfer_flow?createDatabaseIfNotExist=true
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          TRANSFERFLOW_API_GOOGLE_CLIENT_ID: test
          TRANSFERFLOW_API_TOKEN_SECRET_KEY: ${{ secrets.TRANSFERFLOW_API_TOKEN_SECRET_KEY }}
          TRANSFERFLOW_FILE_ENCRYPTION_KEY: f0e1d2c3b4a5968778695a4b3c2d1e0f
          TRANSFERFLOW_FILE_EXPIRY_DATE: 7
          TRANSFERFLOW_FILE_VAULT_MAIN_DIRECTORY: ./.transferflow
          SPRING_PROFILE: testing
        run: ./mvnw --no-transfer-progress clean package

      - name: "Start Spring Boot application"
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/transfer_flow?createDatabaseIfNotExist=true
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          TRANSFERFLOW_API_GOOGLE_CLIENT_ID: test
          TRANSFERFLOW_API_TOKEN_SECRET_KEY: ${{ secrets.TRANSFERFLOW_API_TOKEN_SECRET_KEY }}
          TRANSFERFLOW_FILE_ENCRYPTION_KEY: f0e1d2c3b4a5968778695a4b3c2d1e0f
          TRANSFERFLOW_FILE_EXPIRY_DATE: 7
          TRANSFERFLOW_FILE_VAULT_MAIN_DIRECTORY: ./.transferflow
          SPRING_PROFILE: testing
        run: |
          nohup java -jar target/*.jar --SPRING_PROFILE=testing --SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/transfer_flow?createDatabaseIfNotExist=true --SPRING_DATASOURCE_USERNAME=root --SPRING_DATASOURCE_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }} --TRANSFERFLOW_API_GOOGLE_CLIENT_ID=test --TRANSFERFLOW_API_TOKEN_SECRET_KEY=${{ secrets.TRANSFERFLOW_API_TOKEN_SECRET_KEY }} --SPRING_PROFILE=testing --TRANSFERFLOW_FILE_ENCRYPTION_KEY=f0e1d2c3b4a5968778695a4b3c2d1e0f --TRANSFERFLOW_FILE_EXPIRY_DATE=7 --TRANSFERFLOW_FILE_VAULT_MAIN_DIRECTORY=./.transferflow &
      

      - name: Wait for Spring Boot application to start
        run: sleep 15

      - name: Check if port 80 is open
        uses: nrukavkov/open-ports-check-action@v1
        with:
          port: 8080
          host: 'localhost'
          pause: 1000
          needFail: 'true'
          reverse: 'false'

      - name: Run API Tests
        run: newman run ./src/test/postman/collection.json -e ./src/test/postman/env.json

