name: Build and Publish Docker image to Github Image Repo

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '18'
          distribution: adopt

      - name: Set up Maven
        uses: s4u/maven-settings-action@v2.4.0
        with:
          servers: |
            [{
              "id": "ghcr",
              "username": "${{ github.actor }}",
              "password": "${{ secrets.REGISTRY_PASSWORD }}"
            }]

      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Preparing the Image build
        id: prep
        run: |
          echo "::set-output name=tag::$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')"

      - name: Build and push Docker image
        run: mvn compile jib:build -Djib.to.image=ghcr.io/${{ steps.prep.outputs.tag }} -Djib.to.auth.username="${{ github.actor }}" -Djib.to.auth.password="${{ secrets.REGISTRY_PASSWORD }}"

      - name: Trigger Portainer Webhook
        run: |
          curl --insecure -X POST ${{ secrets.PORTAINER_URL }}
