name: Build and Publish Docker image to Github Image Repo
on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '18'
          distribution: adopt

      - name: Set up Maven
        uses: s4u/maven-settings-action@v2.4.0
        with:
              servers: |
                [{
                "id": "ghcr",
                "username": "${{ github.actor }}",
                "password": "${{ secrets.REGISTRY_PASSWORD }}"
              }]

      - name: Build and push Docker image
        run: mvn compile jib:build -Djib.to.image=ghcr.io/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') -Djib.to.auth.username="${{ github.actor }}" -Djib.to.auth.password="${{ secrets.REGISTRY_PASSWORD }}"

