name: Build and push Docker image
on:
  push:
    branches:
      - master
jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '18'
          distribution: adopt

      - name: Authenticate with GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: registry.hub.docker.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: mvn compile jib:build
