name: Build and Publish Docker image to Github Image Repo
on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '18'
          distribution: adopt

      - name: Authenticate with GitHub Packages to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ${{env.REGISTRY}}
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        run: mvn compile jib:build -Dusername=${{github.actor}} -DimageName=${{github.repository}} -DimageRepository=${{env.REGISTRY}}
