name: Java CI with JUnit tests

on: [pull_request]

jobs:
  build:
    runs-on: self-hosted
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: test-db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
            java-version: '18'
            distribution: adopt

    - name: Run JUnit tests
      env:
        SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/transfer_flow?createDatabaseIfNotExist=true
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        TRANSFERFLOW_API_AUTH_GOOGLE_CLIENT_ID: ${{ secrets.TRANSFERFLOW_API_AUTH_GOOGLE_CLIENT_ID }}
        TRANSFERFLOW_API_TOKEN_SECRET_KEY: ${{ secrets.TRANSFERFLOW_API_TOKEN_SECRET_KEY }}
        SPRING_PROFILE: testing
        TRANSFERFLOW_FILE_ENCRYPTION_KEY: f0e1d2c3b4a5968778695a4b3c2d1e0f
        TRANSFERFLOW_FILE_EXPIRY_DATE: 7
        TRANSFERFLOW_FILE_VAULT_MAIN_DIRECTORY: ./.transferflow
      run: mvn --no-transfer-progress test
